export const EVENTS = [
  {
    id: 'event_pasifika_festival_2026',
    title: 'Pasifika Festival 2026',
    hostOrgId: null,
    nationId: 'aotearoa',
    venue: 'Western Springs, Tāmaki Makaurau',
    startsAt: '2026-03-14T10:00:00+13:00',
    endsAt: '2026-03-15T22:00:00+13:00',
    type: 'in-person',
    description:
      'The largest Pasifika cultural festival in Aotearoa. Eleven village stages, kai, arts pavilion, and the largest gathering of Pacific artists in the country.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 1247,
    linkedArtistIds: ['artist_001', 'artist_003', 'artist_004', 'artist_010'],
  },
  {
    id: 'event_heilala_festival_2026',
    title: 'Heilala Festival — Nuku‘alofa livestream',
    hostOrgId: null,
    nationId: 'tonga',
    venue: 'Nukuʻalofa (livestream across Aotearoa)',
    startsAt: '2026-07-04T11:00:00+13:00',
    endsAt: '2026-07-13T22:00:00+13:00',
    type: 'live-stream',
    description:
      'Tonga\'s national festival, streamed to Aotearoa via community venues. KavaWorks screening partnership with Māngere Arts Centre and Pātaka Art + Museum.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 412,
    linkedArtistIds: ['artist_002', 'persona_elder'],
  },
  {
    id: 'event_samoa_language_week_2026',
    title: 'Sāmoa Language Week 2026',
    hostOrgId: null,
    nationId: 'samoa',
    venue: 'Multi-venue across Aotearoa',
    startsAt: '2026-05-25T09:00:00+12:00',
    endsAt: '2026-05-31T22:00:00+12:00',
    type: 'in-person',
    description:
      'Vaiaso o le Gagana Sāmoa — a week of Sāmoan language and culture with siapo demonstrations, kava ceremonies, workshops, and performances across Aotearoa.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 986,
    linkedArtistIds: ['artist_001', 'artist_010', 'persona_elder'],
  },
  {
    id: 'event_tongan_language_week_2026',
    title: 'Tongan Language Week 2026',
    hostOrgId: null,
    nationId: 'tonga',
    venue: 'Multi-venue across Aotearoa',
    startsAt: '2026-09-06T09:00:00+12:00',
    endsAt: '2026-09-12T22:00:00+12:00',
    type: 'in-person',
    description:
      'Uike Kātoanga\'i \'o e Lea faka-Tonga — a week of Tongan language and culture with ngatu demonstrations, kava ceremonies, and performances.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 541,
    linkedArtistIds: ['artist_002', 'persona_elder'],
  },
  {
    id: 'event_pacific_music_awards_2026',
    title: 'Pacific Music Awards 2026',
    hostOrgId: null,
    nationId: 'aotearoa',
    venue: 'The Civic, Tāmaki Makaurau',
    startsAt: '2026-08-14T19:00:00+12:00',
    endsAt: '2026-08-14T22:30:00+12:00',
    type: 'in-person',
    description:
      'The Pacific Music Awards honour excellence across Pacific music in Aotearoa. Hosted by the Pacific Music Awards Trust.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 284,
    linkedArtistIds: [],
  },
  {
    id: 'event_pacific_arts_summit_2026',
    title: 'Pacific Arts Summit 2026',
    hostOrgId: null,
    nationId: 'aotearoa',
    venue: 'Te Papa Tongarewa, Wellington',
    startsAt: '2026-10-21T09:00:00+13:00',
    endsAt: '2026-10-23T17:00:00+13:00',
    type: 'in-person',
    description:
      'Three-day national summit of Pacific arts practitioners, advisers, funders, and community leaders. Hosted by Creative New Zealand Pacific Arts.',
    coverImageCredit: 'Placeholder — typographic card',
    rsvpCount: 168,
    linkedArtistIds: ['persona_adviser', 'artist_001', 'artist_007', 'artist_012'],
  },
] as const;
