export const NATIONS = [
  {
    id: 'samoa',
    name: 'Sāmoa',
    flag: '🇼🇸',
    greetingMorning: 'Talofa',
    greetingEvening: 'Manuia le afiafi',
    culturalTheme: 'tapa',
    patternId: 'pattern-tapa',
    heritageArtforms: ['siapo', 'tatau', 'fala', 'lālaga'],
    languageCode: 'sm',
    elderTitle: 'Matai',
    culturalNote:
      'Fa\'aaloalo — respect expressed through action, speech, and presence — shapes every Sāmoan creative encounter.',
  },
  {
    id: 'tonga',
    name: 'Tonga',
    flag: '🇹🇴',
    greetingMorning: 'Mālō e lelei',
    greetingEvening: 'Mālō e lelei ki he efiafi',
    culturalTheme: 'koula',
    patternId: 'pattern-koula',
    heritageArtforms: ['ngatu', 'kupesi', 'lālanga'],
    languageCode: 'to',
    elderTitle: 'ʻAtī or Tuʻu',
    culturalNote: 'Tauhi vā — the active tending of relational space — is a Tongan foundation.',
  },
  {
    id: 'fiji',
    name: 'Fiji (Viti)',
    flag: '🇫🇯',
    greetingMorning: 'Bula vinaka',
    greetingEvening: 'Ni sā yadra',
    culturalTheme: 'moana',
    patternId: 'pattern-fiji-masi',
    heritageArtforms: ['masi', 'magimagi', 'kuta'],
    languageCode: 'fj',
    elderTitle: 'Turaga or Marama',
    culturalNote:
      'Masi patterns carry family and village identity; every geometric form has ancestry behind it.',
  },
  {
    id: 'cooks',
    name: 'Cook Islands (Kūki ʻĀirani)',
    flag: '🇨🇰',
    greetingMorning: 'Kia orana',
    greetingEvening: 'Kia manuia',
    culturalTheme: 'ula-fala',
    patternId: 'pattern-cook-tivaevae',
    heritageArtforms: ['tīvaevae', 'rito hats', 'carving'],
    languageCode: 'rar',
    elderTitle: 'Mama or Papa',
    culturalNote:
      'Tīvaevae is a communal quilting tradition — the vanaga (gathering of makers) is part of the work.',
  },
  {
    id: 'niue',
    name: 'Niue',
    flag: '🇳🇺',
    greetingMorning: 'Fakaalofa lahi atu',
    greetingEvening: 'Kia monuina',
    culturalTheme: 'koula',
    patternId: 'pattern-koula',
    heritageArtforms: ['hiapo', 'weaving', 'carving'],
    languageCode: 'niu',
    elderTitle: 'Patu or Fifine Motua',
    culturalNote: 'Inati — equal sharing of the harvest — is a Niuean principle we carry into Drops.',
  },
  {
    id: 'tahiti',
    name: 'Tahiti (Māʻohi Nui)',
    flag: '🇵🇫',
    greetingMorning: 'Ia ora na',
    greetingEvening: 'Ia ora na i te ahiahi',
    culturalTheme: 'tapa',
    patternId: 'pattern-tahiti-tifaifai',
    heritageArtforms: ['tīfaifai', 'tatau', 'monoʻi'],
    languageCode: 'ty',
    elderTitle: 'ʻOrometua or Mama Ruau',
    culturalNote: 'Tahitian tatau patterns carry lineage. Non-Māʻohi tattooers copying them is a live issue.',
  },
  {
    id: 'hawaii',
    name: 'Hawaiʻi',
    flag: '🏝️',
    greetingMorning: 'Aloha',
    greetingEvening: 'Aloha ahiahi',
    culturalTheme: 'moana',
    patternId: 'pattern-hawaii-kapa',
    heritageArtforms: ['kapa', 'lei hulu', 'hula'],
    languageCode: 'haw',
    elderTitle: 'Kupuna',
    culturalNote:
      'Kanaka Maoli — the Native Hawaiian people — shape how kapa and lei hulu are made and shared.',
  },
  {
    id: 'vanuatu',
    name: 'Vanuatu',
    flag: '🇻🇺',
    greetingMorning: 'Halo',
    greetingEvening: 'Halo olketa',
    culturalTheme: 'ula-fala',
    patternId: 'pattern-vanuatu-sand',
    heritageArtforms: ['sand drawing', 'rom masks', 'mats'],
    languageCode: 'bi',
    elderTitle: 'Chief or Jif',
    culturalNote: 'Ni-Vanuatu sand drawing is transient — a practice, not a product. We honour its passing.',
  },
  {
    id: 'png',
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    greetingMorning: 'Gude',
    greetingEvening: 'Gude olgeta',
    culturalTheme: 'niu',
    patternId: 'pattern-png-bilum',
    heritageArtforms: ['bilum', 'mud masks', 'carving'],
    languageCode: 'tpi',
    elderTitle: 'Bigman or Bigmeri',
    culturalNote: 'Bilum loop-weaving is done in the hands, not on a loom. The rhythm carries story.',
  },
  {
    id: 'aotearoa',
    name: 'Aotearoa (Māori)',
    flag: '🇳🇿',
    greetingMorning: 'Kia ora',
    greetingEvening: 'Tēnā koutou i te pō',
    culturalTheme: 'niu',
    patternId: 'pattern-niu',
    heritageArtforms: ['tā moko', 'whakairo', 'rāranga', 'kōwhaiwhai'],
    languageCode: 'mi',
    elderTitle: 'Kaumātua',
    culturalNote: 'Kaitiakitanga — guardianship — sits at the centre of all Māori practice here.',
  },
  {
    id: 'solomons',
    name: 'Solomon Islands',
    flag: '🇸🇧',
    greetingMorning: 'Halo',
    greetingEvening: 'Gudnaet',
    culturalTheme: 'moana',
    patternId: 'pattern-solomons-shell',
    heritageArtforms: ['shell jewellery', 'wood carving'],
    languageCode: 'pis',
    elderTitle: 'Jif or Mama',
    culturalNote: 'Shell money carries exchange and relationship — wearing it is entering a network.',
  },
  {
    id: 'tuvalu',
    name: 'Tuvalu',
    flag: '🇹🇻',
    greetingMorning: 'Tālofa',
    greetingEvening: 'Tālofa i te afiafi',
    culturalTheme: 'ula-fala',
    patternId: 'pattern-tuvalu-fala',
    heritageArtforms: ['fala', 'fans', 'shell work'],
    languageCode: 'tvl',
    elderTitle: 'Toeaina',
    culturalNote: 'Fala weaving is climate work — the material itself is endangered by rising seas.',
  },
  {
    id: 'tokelau',
    name: 'Tokelau',
    flag: '🇹🇰',
    greetingMorning: 'Mālō ni',
    greetingEvening: 'Mālō ni',
    culturalTheme: 'moana',
    patternId: 'pattern-moana',
    heritageArtforms: ['tuluma', 'pandanus weaving'],
    languageCode: 'tkl',
    elderTitle: 'Toeaina',
    culturalNote: 'The tuluma is carved from a single piece of wood. Nothing is imported onto it.',
  },
  {
    id: 'kiribati',
    name: 'Kiribati',
    flag: '🇰🇮',
    greetingMorning: 'Mauri',
    greetingEvening: 'Kam na mauri',
    culturalTheme: 'koula',
    patternId: 'pattern-kiribati-te-bino',
    heritageArtforms: ['te bino', 'stick dance', 'mats'],
    languageCode: 'gil',
    elderTitle: 'Unimwaane',
    culturalNote: 'Te bino is danced. The pattern lives in the body before it lives in a textile.',
  },
] as const;

export type NationId = (typeof NATIONS)[number]['id'];
