import type { ArtistSeed } from './types';

/**
 * The 7 role personas. Each is a "user" the demo can sign in as.
 * The artist persona (Lesā Tupuola Feʻilo) reuses artist_001 from artists-core.
 * The others are distinct records.
 */
export const PERSONAS: ArtistSeed[] = [
  {
    id: 'persona_audience',
    name: 'Reuben Tamatoa',
    handle: 'reubent',
    role: 'audience',
    primaryNationId: 'cooks',
    affiliations: ['cooks', 'aotearoa'],
    city: 'Porirua',
    bio: `Kia orana. I work in the public service by day; I spend my weekends chasing Pacific art around Wellington and the lower North. I follow 47 artists on KavaWorks. I have bought eleven pieces so far.`,
    statement: `I am not an artist. I am a follower. I grew up in Porirua; my grandparents came here in the 1970s. Tīvaevae hung on our walls; my mother sewed some of them. I came to art through family and I stayed because of community.

I support six artists at the Patron tier and two at the Inati Circle tier. I read every studio note that comes in. I do not comment often on posts; I read and save.`,
    avatarStyle: 'illustrated-silhouette',
    verified: false,
    elderStatus: false,
    elderInGroups: [],
    culturalTheme: 'ula-fala',
    artforms: [],
    yearsActive: 0,
    followers: 18,
    following: 47,
    postsCount: 0,
    worksSold: 0,
    supporters: 0,
    awards: [],
    subscriptionTiers: [],
    exhibitions: [],
    lineage: {},
  },
  {
    id: 'persona_collector',
    name: 'Hinemoa Kealoha-Parker',
    handle: 'hinemoakp',
    role: 'collector',
    primaryNationId: 'aotearoa',
    affiliations: ['aotearoa', 'hawaii'],
    city: 'Parnell, Tāmaki Makaurau',
    bio: `Tēnā koutou. I am Māori (Ngāi Tahu) and Kanaka Maoli on my mother\'s side. I have been collecting Pacific art seriously since 2004. Current collection: 120 pieces across siapo, ngatu, kapa, masi, tīvaevae, carving, photography, and jewellery.`,
    statement: `I think of collecting as one form of tautua — the Sāmoan principle of service. I serve by acquiring. The works go on my walls for my children and grandchildren to live with, and eventually — this is documented — most of them go to public collections.

I do not collect to appreciate. I collect to circulate. Half my collection has been loaned to exhibitions in the past decade.

I support twenty-two artists at the Inati Circle tier. I do not attend openings where artists are not paid. I ask for provenance that includes artist voice, not just gallery receipts.`,
    avatarStyle: 'illustrated-silhouette',
    verified: true,
    elderStatus: false,
    elderInGroups: [],
    culturalTheme: 'niu',
    artforms: [],
    yearsActive: 0,
    followers: 231,
    following: 174,
    postsCount: 4,
    worksSold: 0,
    supporters: 0,
    awards: [],
    subscriptionTiers: [],
    exhibitions: [],
    lineage: {},
  },
  {
    id: 'persona_org',
    name: 'Māngere Arts Centre — Ngā Tohu o Uenuku',
    handle: 'mangerearts',
    role: 'org',
    primaryNationId: 'aotearoa',
    affiliations: ['aotearoa', 'samoa', 'tonga', 'cooks'],
    city: 'Māngere, Tāmaki Makaurau',
    bio: `Māngere Arts Centre — Ngā Tohu o Uenuku is a council-owned, community-run arts venue in Māngere, Auckland. We programme Pasifika and Māori artists across visual, performance, and community arts.`,
    statement: `We opened in 2009. Our name, Ngā Tohu o Uenuku, was gifted by local iwi and means "the signs of the rainbow" — a welcome to many peoples. Our programme is 70% Pasifika and Māori; 30% other. We pay artist fees that meet CNZ guidelines and we publish our pay scales openly.`,
    avatarStyle: 'illustrated-silhouette',
    verified: true,
    elderStatus: false,
    elderInGroups: [],
    culturalTheme: 'moana',
    artforms: [],
    yearsActive: 17,
    followers: 4210,
    following: 89,
    postsCount: 312,
    worksSold: 0,
    supporters: 0,
    awards: [],
    subscriptionTiers: [],
    exhibitions: [],
    lineage: {},
    orgInfo: {
      mission:
        'Ngā Tohu o Uenuku is a home for Pasifika and Māori arts practice in South Auckland. We programme artists who shape the ecosystem, we host community wānanga, and we pay properly.',
      staff: [
        'Lolomanaia Toma — Director',
        'Vaine Rasmussen — Pacific Programmes Lead',
        'Hemi Pounamu — Māori Programmes Lead',
        'Anapela Tualaulelei — Community Partnerships',
      ],
      foundedYear: 2009,
      focus: ['Pacific arts', 'Māori arts', 'community arts', 'youth development'],
    },
  },
  {
    id: 'persona_adviser',
    name: 'Semisi Falepapalangi',
    handle: 'semisicnz',
    role: 'adviser',
    primaryNationId: 'tonga',
    affiliations: ['tonga', 'aotearoa'],
    city: 'Te Whanganui-a-Tara (Wellington)',
    bio: `Mālō e lelei. I am a Practice Adviser for Pacific Arts (fictional demo role modelled on the Creative New Zealand Pacific Arts team). I work with a caseload of 24 artists across visual, craft, performance, and literature.`,
    statement: `My job is to remove friction between Pasifika artists and funding. That is it. I read drafts. I book kōrero. I walk people through eligibility. I do not write applications for artists — that would be the wrong kind of help — but I read, and I give feedback.

I hold office hours on Tuesdays, 10am–4pm, in person in Wellington or by Zoom. Book through the CNZ portal or email me directly.

I was a practising artist before I became an adviser. I know what it feels like to stare at an application form at 2am. My role is to make that 2am moment rare.`,
    avatarStyle: 'illustrated-silhouette',
    verified: true,
    elderStatus: false,
    elderInGroups: [],
    culturalTheme: 'koula',
    artforms: [],
    yearsActive: 8,
    followers: 1402,
    following: 241,
    postsCount: 38,
    worksSold: 0,
    supporters: 0,
    awards: [],
    subscriptionTiers: [],
    exhibitions: [],
    lineage: {},
    expertise: ['Grants navigation', 'Pacific Arts funding', 'Mid-career transitions', 'Application review'],
    officeHours: 'Tuesdays 10am–4pm. Book a kōrero via the CNZ portal.',
  },
  {
    id: 'persona_elder',
    name: 'Matai Tuiʻi Alefaio',
    handle: 'tuiialefaio',
    role: 'elder',
    primaryNationId: 'samoa',
    affiliations: ['samoa', 'aotearoa'],
    city: 'Māngere, Tāmaki Makaurau',
    bio: `Talofa. I am matai in my ʻāiga and elder in the Sāmoan Weavers group on KavaWorks. My primary practice is siapo, which I have been making for thirty-eight years. I teach Saturday wānanga with Lesā Tupuola Feʻilo.`,
    statement: `Being an elder here is the same work as being an elder anywhere. I hold the vā. I do not speak first in a thread unless asked. I do not bless a post casually. Blessing in the old way meant something, and I refuse to let it become an Instagram react.

I am approving new members of the Sāmoan Weavers group when they come. I am writing the charter. I am correcting language where it drifts. I am not here to moderate in a Western sense — I am here to keep the space warm.

Mālō lava.`,
    avatarStyle: 'illustrated-silhouette',
    verified: true,
    elderStatus: true,
    elderInGroups: ['group_siapo_makers', 'group_tongan_weavers'],
    culturalTheme: 'tapa',
    artforms: ['siapo'],
    yearsActive: 38,
    followers: 2104,
    following: 98,
    postsCount: 72,
    worksSold: 17,
    supporters: 28,
    awards: [],
    subscriptionTiers: [
      { name: 'Supporter', priceNzd: 5, perks: ['Monthly wānanga photo'] },
    ],
    exhibitions: [
      { year: 2018, title: 'Tapa Pacific', venue: 'Te Papa Tongarewa', role: 'Group' },
    ],
    lineage: {
      apprenticedTo: 'My mother and two aunties in Sāmoa',
      teaches: ['Māngere Saturday wānanga'],
      exhibitedWith: ['lesatupuola'],
    },
  },
  {
    id: 'persona_admin',
    name: 'Kava Team',
    handle: 'kavateam',
    role: 'admin',
    primaryNationId: 'aotearoa',
    affiliations: ['aotearoa'],
    city: 'Wellington / Auckland / remote',
    bio: `Kia ora — we are the KavaWorks platform team. This account appears only in admin view. We do not post.`,
    statement: `Our role is to hold the platform. We do not programme content beyond editorial picks for the Feed hero rotation, and those picks are made in partnership with advisers. We do not surveil individual users. Our platform metrics are aggregate only.

We moderate as little as possible. Most moderation is elder-led, inside groups, by designation. We respond to flagged items within 48 hours.`,
    avatarStyle: 'illustrated-silhouette',
    verified: true,
    elderStatus: false,
    elderInGroups: [],
    culturalTheme: 'moana',
    artforms: [],
    yearsActive: 0,
    followers: 0,
    following: 0,
    postsCount: 0,
    worksSold: 0,
    supporters: 0,
    awards: [],
    subscriptionTiers: [],
    exhibitions: [],
    lineage: {},
  },
];
