import type { PostSeed } from './types';

/**
 * 28 posts + 16 "shorts" (posts with mediaType: 'video' and durationSec set).
 * Distribution per brief § 8.4:
 *  - 8 process, 6 finished-work, 4 teaching, 3 announcement, 3 community,
 *    2 collaboration, 2 tapu.
 * Language coverage: 10 Pacific languages with translations.
 */
export const POSTS: PostSeed[] = [
  // --- Process posts ---
  {
    id: 'post_001',
    authorId: 'artist_001',
    mediaType: 'image',
    mediaRef: 'post_001',
    caption:
      'Ua mae a uō le siapo nei i le itū o Leulumoega, i le tausaga a tausaga. Today I am finishing a piece my grandmother started.',
    captionLang: 'sm',
    captionTranslation:
      'This siapo has been four years in the making, in the way of Leulumoega. Today I am finishing a piece my grandmother started.',
    tapu: false,
    nationId: 'samoa',
    artform: 'siapo',
    collaboratorHandles: [],
    createdAt: '2026-04-18T09:12:00+12:00',
    likes: 247,
    comments: 18,
    shares: 12,
    saves: 89,
    views: 2840,
    commentsData: [
      {
        authorHandle: 'akanisi_t',
        text: 'Vinaka for sharing this with us, Lesā.',
        createdAt: '2026-04-18T10:02:00+12:00',
      },
      {
        authorHandle: 'tuiialefaio',
        text: 'Lau tuatua — your hands carry your grandmother\'s.',
        createdAt: '2026-04-18T11:40:00+12:00',
        elderMark: true,
      },
      {
        authorHandle: 'teremoana_nt',
        text: 'Thinking of you as you close this piece.',
        createdAt: '2026-04-18T13:15:00+12:00',
      },
    ],
  },
  {
    id: 'post_002',
    authorId: 'artist_007',
    mediaType: 'video',
    mediaRef: 'post_002_video',
    posterRef: 'post_002_poster',
    durationSec: 42,
    caption:
      'The first beating of the wauke. Each morning I wait until the mist clears over Mauna Kea before I start. Different rhythm from the siapo I watch here — mine comes from Hilo.',
    captionLang: 'en',
    tapu: false,
    nationId: 'hawaii',
    artform: 'kapa',
    collaboratorHandles: [],
    createdAt: '2026-04-17T07:30:00+12:00',
    likes: 412,
    comments: 24,
    shares: 31,
    saves: 156,
    views: 8420,
    commentsData: [
      {
        authorHandle: 'lesatupuola',
        text: 'The different rhythms of our bark — beautiful.',
        createdAt: '2026-04-17T08:50:00+12:00',
      },
      {
        authorHandle: 'folatalagi',
        text: 'I have been waiting for this video.',
        createdAt: '2026-04-17T09:12:00+12:00',
      },
    ],
  },
  {
    id: 'post_003',
    authorId: 'artist_004',
    mediaType: 'image',
    mediaRef: 'post_003',
    caption:
      'Kia orana. Tuesday night vanaga. Nine of us around the table, two of my daughters on the floor underneath it. The tīvaevae is for a wedding in October.',
    captionLang: 'rar',
    captionTranslation: 'Tuesday night gathering — nine of us at the table.',
    tapu: false,
    nationId: 'cooks',
    artform: 'tīvaevae',
    collaboratorHandles: [],
    createdAt: '2026-04-15T21:10:00+12:00',
    likes: 184,
    comments: 22,
    shares: 8,
    saves: 47,
    views: 2104,
    commentsData: [],
  },
  {
    id: 'post_004',
    authorId: 'artist_005',
    mediaType: 'video',
    mediaRef: 'post_004_video',
    posterRef: 'post_004_poster',
    durationSec: 58,
    caption:
      'First chisel cut of a new piece. Pohutukawa — the wood holds the cut cleanly. My great-uncle reviewed the design last week.',
    captionLang: 'en',
    tapu: false,
    nationId: 'niue',
    artform: 'carving',
    collaboratorHandles: [],
    createdAt: '2026-04-14T10:30:00+12:00',
    likes: 156,
    comments: 9,
    shares: 4,
    saves: 62,
    views: 3210,
    commentsData: [],
  },
  {
    id: 'post_005',
    authorId: 'artist_009',
    mediaType: 'video',
    mediaRef: 'post_005_video',
    posterRef: 'post_005_poster',
    durationSec: 31,
    caption:
      'One loop, one finger, one loop, one finger. Melpa bilum close-up. Tenkyu tumas for watching.',
    captionLang: 'tpi',
    captionTranslation: 'Melpa bilum close-up. Thank you so much for watching.',
    tapu: false,
    nationId: 'png',
    artform: 'bilum',
    collaboratorHandles: [],
    createdAt: '2026-04-12T14:00:00+12:00',
    likes: 321,
    comments: 16,
    shares: 27,
    saves: 104,
    views: 5820,
    commentsData: [],
  },
  {
    id: 'post_006',
    authorId: 'artist_003',
    mediaType: 'video',
    mediaRef: 'post_006_video',
    posterRef: 'post_006_poster',
    durationSec: 47,
    caption:
      'Bula vinaka. Masi pattern painting — the triangle cluster you see is our Veidogo vocabulary. Each family has their own.',
    captionLang: 'fj',
    captionTranslation: 'Good day. Masi pattern painting — these triangles are our Veidogo family vocabulary.',
    tapu: false,
    nationId: 'fiji',
    artform: 'masi',
    collaboratorHandles: [],
    createdAt: '2026-04-11T11:15:00+12:00',
    likes: 198,
    comments: 11,
    shares: 6,
    saves: 68,
    views: 2947,
    commentsData: [],
  },
  {
    id: 'post_007',
    authorId: 'artist_011',
    mediaType: 'image',
    mediaRef: 'post_007',
    caption:
      'Halo olgeta. Beach-recovered shell, washed and sorted. Ready for stringing this weekend.',
    captionLang: 'pis',
    captionTranslation: 'Hello everyone. Beach-recovered shell, washed and sorted.',
    tapu: false,
    nationId: 'solomons',
    artform: 'shell jewellery',
    collaboratorHandles: [],
    createdAt: '2026-04-09T15:40:00+12:00',
    likes: 132,
    comments: 4,
    shares: 3,
    saves: 19,
    views: 1420,
    commentsData: [],
  },
  {
    id: 'post_008',
    authorId: 'artist_008',
    mediaType: 'image',
    mediaRef: 'post_008',
    caption:
      'Halo. Last week I drew in the sand at Ōwhiro Bay and the tide took it before sundown. That is the work. This photograph is the documentation.',
    captionLang: 'bi',
    captionTranslation: 'Hello. The sand drawing is gone; the photograph is documentation.',
    tapu: false,
    nationId: 'vanuatu',
    artform: 'sand drawing',
    collaboratorHandles: [],
    createdAt: '2026-04-08T18:20:00+12:00',
    likes: 267,
    comments: 14,
    shares: 18,
    saves: 82,
    views: 3987,
    commentsData: [],
  },
  // --- Finished-work posts ---
  {
    id: 'post_009',
    authorId: 'artist_001',
    mediaType: 'image',
    mediaRef: 'post_009',
    caption:
      'Moana Whakapapa I — complete. 1.8m × 1.2m. Available now in the marketplace. 95% of the sale goes direct.',
    captionLang: 'en',
    tapu: false,
    nationId: 'samoa',
    artform: 'siapo',
    collaboratorHandles: [],
    createdAt: '2026-04-02T09:15:00+12:00',
    likes: 389,
    comments: 27,
    shares: 41,
    saves: 152,
    views: 6214,
    commentsData: [],
  },
  {
    id: 'post_010',
    authorId: 'artist_004',
    mediaType: 'image',
    mediaRef: 'post_010',
    caption:
      'Vanaga Tīvaevae — Porirua is finished. Ten weeks. Nine pairs of hands. In the marketplace now.',
    captionLang: 'en',
    tapu: false,
    nationId: 'cooks',
    artform: 'tīvaevae',
    collaboratorHandles: [],
    createdAt: '2026-04-10T09:30:00+12:00',
    likes: 412,
    comments: 38,
    shares: 22,
    saves: 141,
    views: 5890,
    commentsData: [],
  },
  {
    id: 'post_011',
    authorId: 'artist_007',
    mediaType: 'image',
    mediaRef: 'post_011',
    caption:
      'Kapa — Hilo Rain, complete. Six weeks of beating, two weeks of dyeing. Priced honestly at $8,400.',
    captionLang: 'en',
    tapu: false,
    nationId: 'hawaii',
    artform: 'kapa',
    collaboratorHandles: [],
    createdAt: '2026-03-30T10:00:00+12:00',
    likes: 298,
    comments: 19,
    shares: 14,
    saves: 87,
    views: 4102,
    commentsData: [],
  },
  {
    id: 'post_012',
    authorId: 'artist_009',
    mediaType: 'image',
    mediaRef: 'post_012',
    caption:
      'Wamage dress — Melpa Blue. 80 loop-hours. Priced honestly for the labour inside it.',
    captionLang: 'en',
    tapu: false,
    nationId: 'png',
    artform: 'fashion',
    collaboratorHandles: [],
    createdAt: '2026-04-08T11:00:00+12:00',
    likes: 574,
    comments: 41,
    shares: 52,
    saves: 198,
    views: 8412,
    commentsData: [],
  },
  {
    id: 'post_013',
    authorId: 'artist_012',
    mediaType: 'image',
    mediaRef: 'post_013',
    caption:
      'Tālofa. Funafuti Shore — No. 6 is now available in the marketplace. Funds go to film completion and to Tuvalu-based adaptation groups.',
    captionLang: 'tvl',
    captionTranslation: 'Hello. Funafuti Shore — No. 6 is now available.',
    tapu: false,
    nationId: 'tuvalu',
    artform: 'photography',
    collaboratorHandles: [],
    createdAt: '2026-02-10T09:30:00+12:00',
    likes: 234,
    comments: 16,
    shares: 11,
    saves: 72,
    views: 3421,
    commentsData: [],
  },
  {
    id: 'post_014',
    authorId: 'artist_006',
    mediaType: 'image',
    mediaRef: 'post_014',
    caption:
      'Ia ora na. Line Work — Series III, plate 2 is in the marketplace. Painting, not tatau. Tatau cannot be sold.',
    captionLang: 'ty',
    captionTranslation: 'Hello. This is painting, not tatau. Tatau cannot be sold.',
    tapu: false,
    nationId: 'tahiti',
    artform: 'painting',
    collaboratorHandles: [],
    createdAt: '2026-02-28T10:30:00+12:00',
    likes: 189,
    comments: 7,
    shares: 4,
    saves: 54,
    views: 2671,
    commentsData: [],
  },
  // --- Teaching posts ---
  {
    id: 'post_015',
    authorId: 'artist_001',
    mediaType: 'image',
    mediaRef: 'post_015',
    caption:
      'Saturday wānanga this week — nine of us in the garage. New u\'a is here, new dye is prepared. If you are in Auckland and want to come, DM.',
    captionLang: 'en',
    tapu: false,
    nationId: 'samoa',
    artform: 'siapo',
    collaboratorHandles: [],
    createdAt: '2026-04-05T08:00:00+12:00',
    likes: 167,
    comments: 12,
    shares: 6,
    saves: 44,
    views: 2104,
    commentsData: [],
  },
  {
    id: 'post_016',
    authorId: 'artist_003',
    mediaType: 'image',
    mediaRef: 'post_016',
    caption:
      'This week\'s youth wānanga. Twelve young Fijian-NZ kids, all making their first masi panels. I am in awe of them every week.',
    captionLang: 'en',
    tapu: false,
    nationId: 'fiji',
    artform: 'masi',
    collaboratorHandles: [],
    createdAt: '2026-04-04T17:00:00+12:00',
    likes: 321,
    comments: 23,
    shares: 19,
    saves: 68,
    views: 4120,
    commentsData: [],
  },
  {
    id: 'post_017',
    authorId: 'artist_011',
    mediaType: 'image',
    mediaRef: 'post_017',
    caption:
      'Saturday morning at Manukau. Twenty young Solomons-NZ kids today. Free class, free materials, open every Saturday.',
    captionLang: 'en',
    tapu: false,
    nationId: 'solomons',
    artform: 'shell jewellery',
    collaboratorHandles: [],
    createdAt: '2026-04-04T12:00:00+12:00',
    likes: 198,
    comments: 15,
    shares: 9,
    saves: 31,
    views: 2780,
    commentsData: [],
  },
  {
    id: 'post_018',
    authorId: 'artist_007',
    mediaType: 'image',
    mediaRef: 'post_018',
    caption:
      'Aloha. Kapa workshop series at Waikato Pasifika community centre starts 2 May. Six Saturdays. Open to Kanaka Maoli and other Polynesian makers first; public seats open second week.',
    captionLang: 'en',
    tapu: false,
    nationId: 'hawaii',
    artform: 'kapa',
    collaboratorHandles: [],
    createdAt: '2026-04-10T09:00:00+12:00',
    likes: 144,
    comments: 18,
    shares: 22,
    saves: 47,
    views: 2310,
    commentsData: [],
  },
  // --- Announcement posts ---
  {
    id: 'post_019',
    authorId: 'artist_002',
    mediaType: 'image',
    mediaRef: 'post_019',
    caption:
      'Mālō e lelei. The Sea is Us — prints from the Objectspace show are available. Edition of 8. $540 per print. Signed.',
    captionLang: 'to',
    captionTranslation: 'Hello. Prints from the Objectspace show are now available.',
    tapu: false,
    nationId: 'tonga',
    artform: 'photography',
    collaboratorHandles: [],
    createdAt: '2026-01-18T11:00:00+12:00',
    likes: 412,
    comments: 28,
    shares: 19,
    saves: 134,
    views: 6104,
    commentsData: [],
  },
  {
    id: 'post_020',
    authorId: 'artist_005',
    mediaType: 'image',
    mediaRef: 'post_020',
    caption:
      'Fakaalofa lahi atu. My first Drop — 24 carvings, 24-hour inati window, opens Thursday 7am. I am nervous. Thank you for being here.',
    captionLang: 'niu',
    captionTranslation: 'Hello. My first Drop — 24 carvings, 24-hour window, opens Thursday 7am.',
    tapu: false,
    nationId: 'niue',
    artform: 'carving',
    collaboratorHandles: [],
    createdAt: '2026-04-20T10:00:00+12:00',
    likes: 287,
    comments: 32,
    shares: 28,
    saves: 98,
    views: 4210,
    commentsData: [],
  },
  {
    id: 'post_021',
    authorId: 'artist_010',
    mediaType: 'audio',
    mediaRef: 'post_021_audio',
    posterRef: 'post_021_poster',
    durationSec: 134,
    caption:
      'Tēnā koutou. New audio piece — "Three Tongues" — is on my Bandcamp now. Two minutes fourteen. Free listen; pay what you can.',
    captionLang: 'mi',
    captionTranslation: 'Hello. New audio piece is out.',
    tapu: false,
    nationId: 'aotearoa',
    artform: 'spoken word',
    collaboratorHandles: [],
    createdAt: '2026-04-16T16:00:00+12:00',
    likes: 341,
    comments: 19,
    shares: 41,
    saves: 87,
    views: 4812,
    commentsData: [],
  },
  // --- Community posts ---
  {
    id: 'post_022',
    authorId: 'persona_org',
    mediaType: 'image',
    mediaRef: 'post_022',
    caption:
      'Opening night at Ngā Tohu o Uenuku — Lesā Tupuola Feʻilo\'s Whenua Whakapapa. Thank you to everyone who came. Full house.',
    captionLang: 'en',
    tapu: false,
    nationId: 'aotearoa',
    artform: 'siapo',
    collaboratorHandles: ['lesatupuola'],
    createdAt: '2024-10-05T22:00:00+13:00',
    likes: 421,
    comments: 24,
    shares: 18,
    saves: 67,
    views: 5120,
    commentsData: [],
  },
  {
    id: 'post_023',
    authorId: 'artist_002',
    mediaType: 'image',
    mediaRef: 'post_023',
    caption:
      'Queer Pasifika gathering at BATS last night. Eighteen artists in the room. Most of them collaborators on the ngatu-photography project at different points.',
    captionLang: 'en',
    tapu: false,
    nationId: 'tonga',
    artform: 'photography',
    collaboratorHandles: [],
    createdAt: '2026-04-12T08:00:00+12:00',
    likes: 204,
    comments: 11,
    shares: 8,
    saves: 38,
    views: 2640,
    commentsData: [],
  },
  {
    id: 'post_024',
    authorId: 'persona_elder',
    mediaType: 'image',
    mediaRef: 'post_024',
    caption:
      'Talofa. This morning I blessed Lesā\'s new piece before she sent it out. A small ceremony. The vā is held.',
    captionLang: 'en',
    tapu: false,
    nationId: 'samoa',
    artform: 'siapo',
    collaboratorHandles: ['lesatupuola'],
    createdAt: '2026-04-02T11:00:00+12:00',
    likes: 267,
    comments: 14,
    shares: 9,
    saves: 52,
    views: 3104,
    commentsData: [],
  },
  // --- Collaboration posts ---
  {
    id: 'post_025',
    authorId: 'artist_002',
    mediaType: 'image',
    mediaRef: 'post_025',
    caption:
      'Collab with Akanisi — photographic print layered over her masi pattern. An experiment. We will see if it works.',
    captionLang: 'en',
    tapu: false,
    nationId: 'tonga',
    artform: 'photography',
    collaboratorHandles: ['akanisi_t'],
    createdAt: '2026-04-11T13:30:00+12:00',
    likes: 176,
    comments: 12,
    shares: 7,
    saves: 41,
    views: 2340,
    commentsData: [],
  },
  {
    id: 'post_026',
    authorId: 'artist_009',
    mediaType: 'image',
    mediaRef: 'post_026',
    caption:
      'With Faith Hanuili on a bilum-and-shell piece. Melpa bilum bodice, Solomons shell trim. Not commercial. A gift between two shops.',
    captionLang: 'en',
    tapu: false,
    nationId: 'png',
    artform: 'fashion',
    collaboratorHandles: ['faith_h'],
    createdAt: '2026-04-07T14:00:00+12:00',
    likes: 412,
    comments: 24,
    shares: 18,
    saves: 92,
    views: 5341,
    commentsData: [],
  },
  // --- Tapu posts ---
  {
    id: 'post_027',
    authorId: 'artist_001',
    mediaType: 'image',
    mediaRef: 'post_027',
    caption:
      'Piece for a Leulumoega funeral next month. Tapu — visible only to Sāmoan Weavers and the affected ʻāiga.',
    captionLang: 'sm',
    captionTranslation: 'Piece for a family funeral. Tapu.',
    tapu: true,
    nationId: 'samoa',
    artform: 'siapo',
    collaboratorHandles: [],
    createdAt: '2026-04-16T17:00:00+12:00',
    likes: 42,
    comments: 6,
    shares: 0,
    saves: 8,
    views: 89,
    commentsData: [],
  },
  {
    id: 'post_028',
    authorId: 'artist_006',
    mediaType: 'image',
    mediaRef: 'post_028',
    caption:
      'Tatau process — tapu. Shared here only with Māʻohi, Māori, and Pasifika members. The mark and the client do not leave this group.',
    captionLang: 'ty',
    captionTranslation: 'Tatau process — tapu.',
    tapu: true,
    nationId: 'tahiti',
    artform: 'tatau',
    collaboratorHandles: [],
    createdAt: '2026-04-03T14:00:00+12:00',
    likes: 78,
    comments: 12,
    shares: 0,
    saves: 21,
    views: 184,
    commentsData: [],
  },
];
