import type { WorkSeed } from './types';

export const WORKS: WorkSeed[] = [
  {
    id: 'work_001',
    artistId: 'artist_001',
    title: 'Moana Whakapapa I',
    description: `A large siapo on hand-beaten u\'a, dyed with ʻoʻa (Bischofia javanica) and soa (Parinari insularum). The central motif — a diamond-enclosed four-point star — is from my grandmother\'s stamp, which she used on the shoulder of my mother\'s wedding siapo in 1978. The border patterns are mine. This piece is the first in a series of three.`,
    priceNzd: 4800,
    mediaRefs: ['work_001_main', 'work_001_detail_1', 'work_001_detail_2'],
    artform: 'siapo',
    nationId: 'samoa',
    materials: 'U\'a (paper mulberry bark), ʻoʻa and soa dyes, kōkōwai',
    dimensions: '1.8m × 1.2m',
    yearMade: 2025,
    culturalStory:
      'This siapo carries the patterns of Leulumoega, passed from my grandmother Tupu to me in 1998. The central motif is from her hand; the borders are mine. It is the first of a series of three.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-04-02T09:00:00+12:00',
  },
  {
    id: 'work_002',
    artistId: 'artist_001',
    title: 'Leulumoega Daughter',
    description: `A smaller siapo commissioned by a Leulumoega family for their daughter\'s 21st. Central stamp is the family\'s crest; borders reference the shoreline at Leulumoega where the u\'a is harvested.`,
    priceNzd: 2200,
    mediaRefs: ['work_002_main', 'work_002_detail'],
    artform: 'siapo',
    nationId: 'samoa',
    materials: 'U\'a, ʻoʻa, kōkōwai',
    dimensions: '1.0m × 0.8m',
    yearMade: 2025,
    culturalStory:
      'Commissioned piece with family consent to exhibit. The crest is used with the family\'s permission; I cannot sell that crest outside the family line but they have released this particular piece for resale in case of family need.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-03-18T09:00:00+12:00',
  },
  {
    id: 'work_003',
    artistId: 'artist_001',
    title: 'Tupu Series — Stamp No. 4',
    description: `A limited-edition print taken directly from one of my grandmother\'s original stamps. Edition of 24. The stamp carries 1978 — the year my mother was married.`,
    priceNzd: 380,
    mediaRefs: ['work_003_main'],
    artform: 'printmaking',
    nationId: 'samoa',
    materials: 'Archival ink on heritage paper',
    dimensions: '60cm × 45cm',
    edition: { number: 7, of: 24 },
    yearMade: 2025,
    culturalStory:
      'My grandmother\'s original stamp, preserved. This print is with family blessing and the edition is fixed at 24 — one for each year she made siapo between her first and last pieces.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-02-14T09:00:00+12:00',
  },
  {
    id: 'work_004',
    artistId: 'artist_001',
    title: 'Whenua Whakapapa III',
    description: `The third in the Whenua Whakapapa series. Large-format siapo, exhibited at Māngere Arts Centre in 2024 as part of my solo show. This piece was the centrepiece.`,
    priceNzd: 9500,
    mediaRefs: ['work_004_main', 'work_004_detail_1', 'work_004_detail_2', 'work_004_detail_3'],
    artform: 'siapo',
    nationId: 'samoa',
    materials: 'U\'a, ʻoʻa, soa, kōkōwai',
    dimensions: '2.4m × 1.6m',
    yearMade: 2024,
    culturalStory:
      'The Whenua Whakapapa series maps my lineage across two oceans — Leulumoega on one side, Māngere on the other. This third piece closes the arc with my daughters\' names rendered in traditional stamp vocabulary at the lower register.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2024-10-01T09:00:00+12:00',
  },
  {
    id: 'work_005',
    artistId: 'artist_003',
    title: 'Masi Matua — Veidogo',
    description: `Framed masi from Veidogo tradition. The central triangle cluster represents the hill behind the village; the horizontal bands represent the three generations of women in my family who have made masi.`,
    priceNzd: 1600,
    mediaRefs: ['work_005_main', 'work_005_detail'],
    artform: 'masi',
    nationId: 'fiji',
    materials: 'Masi bark, natural dye, archival frame',
    dimensions: '90cm × 60cm',
    yearMade: 2025,
    culturalStory:
      'Veidogo masi carries hill, shore, and family. This piece is from my own family vocabulary, made with my aunt\'s blessing for sale outside the village.',
    status: 'live',
    shippingFrom: 'Hamilton, Aotearoa',
    tapu: false,
    createdAt: '2026-03-05T09:00:00+12:00',
  },
  {
    id: 'work_006',
    artistId: 'artist_003',
    title: 'Youth Masi (2025 cohort composite)',
    description: `A composite piece made collaboratively with twelve young Fijian-NZ artists from the Kirikiriroa Saturday wānanga. Each contributed a central panel; I stitched them together. All proceeds go back to the wānanga materials fund.`,
    priceNzd: 650,
    mediaRefs: ['work_006_main', 'work_006_detail'],
    artform: 'masi',
    nationId: 'fiji',
    materials: 'Masi bark, natural dye',
    dimensions: '1.2m × 0.9m',
    yearMade: 2025,
    culturalStory:
      'Made across twelve weeks by twelve young makers. Each panel is named. Sale funds go to the wānanga material budget for the 2026 cohort.',
    status: 'live',
    shippingFrom: 'Hamilton, Aotearoa',
    tapu: false,
    createdAt: '2026-03-28T09:00:00+12:00',
  },
  {
    id: 'work_007',
    artistId: 'artist_004',
    title: 'Vanaga Tīvaevae — Porirua',
    description: `Large tīvaevae, stitched across ten weeks in the Porirua Tuesday vanaga. Nine pairs of hands. Colours reference the Porirua harbour at dusk.`,
    priceNzd: 4200,
    mediaRefs: ['work_007_main', 'work_007_detail_1', 'work_007_detail_2'],
    artform: 'tīvaevae',
    nationId: 'cooks',
    materials: 'Cotton, polyester thread',
    dimensions: '2.1m × 2.1m',
    yearMade: 2025,
    culturalStory:
      'Made in vanaga. Nine women, ten weeks, shared hands. My name is on the piece but the hands are collective.',
    status: 'live',
    shippingFrom: 'Porirua, Aotearoa',
    tapu: false,
    createdAt: '2026-04-10T09:00:00+12:00',
  },
  {
    id: 'work_008',
    artistId: 'artist_004',
    title: 'Tīvaevae cushion — sunset',
    description: `A cushion-sized tīvaevae panel, finished solo at my kitchen table. Coral, apricot, ochre.`,
    priceNzd: 220,
    mediaRefs: ['work_008_main'],
    artform: 'tīvaevae',
    nationId: 'cooks',
    materials: 'Cotton, polyester thread, linen backing',
    dimensions: '50cm × 50cm',
    yearMade: 2025,
    culturalStory: 'A solo piece in the traditional manu pattern vocabulary.',
    status: 'live',
    shippingFrom: 'Porirua, Aotearoa',
    tapu: false,
    createdAt: '2026-04-01T09:00:00+12:00',
  },
  {
    id: 'work_009',
    artistId: 'artist_004',
    title: 'Tīvaevae cushion — harbour',
    description: `Companion to Tīvaevae cushion — sunset. Teal, navy, grey.`,
    priceNzd: 220,
    mediaRefs: ['work_009_main'],
    artform: 'tīvaevae',
    nationId: 'cooks',
    materials: 'Cotton, polyester thread, linen backing',
    dimensions: '50cm × 50cm',
    yearMade: 2025,
    culturalStory: 'Porirua harbour palette in manu vocabulary.',
    status: 'live',
    shippingFrom: 'Porirua, Aotearoa',
    tapu: false,
    createdAt: '2026-04-01T09:00:00+12:00',
  },
  {
    id: 'work_010',
    artistId: 'artist_005',
    title: 'Tumau (contemporary)',
    description: `A single carved piece in pohutukawa, extending Niuean tumau vocabulary into a contemporary sculptural form. Reviewed by my great-uncle Tagaloa before release.`,
    priceNzd: 2800,
    mediaRefs: ['work_010_main', 'work_010_detail_1', 'work_010_detail_2'],
    artform: 'carving',
    nationId: 'niue',
    materials: 'Pohutukawa, beeswax finish',
    dimensions: '90cm × 25cm × 25cm',
    yearMade: 2025,
    culturalStory:
      'Form extends the tumau vocabulary my great-uncle Tagaloa taught me. He has approved this piece for sale.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-03-22T09:00:00+12:00',
  },
  {
    id: 'work_011',
    artistId: 'artist_005',
    title: 'Small tumau study — cedar',
    description: `A study piece in cedar. Part of the carving series that preceded the larger pohutukawa works.`,
    priceNzd: 420,
    mediaRefs: ['work_011_main'],
    artform: 'carving',
    nationId: 'niue',
    materials: 'Western red cedar, oil finish',
    dimensions: '40cm × 12cm × 12cm',
    yearMade: 2025,
    culturalStory: 'A study, not a ceremonial piece. Safe for any home.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-03-12T09:00:00+12:00',
  },
  {
    id: 'work_012',
    artistId: 'artist_006',
    title: 'Line Work — Series III, plate 2',
    description: `Large painting in acrylic on linen. Tatau vocabulary rendered abstractly at scale. This is painting, not tatau. The difference matters.`,
    priceNzd: 6800,
    mediaRefs: ['work_012_main', 'work_012_detail'],
    artform: 'painting',
    nationId: 'tahiti',
    materials: 'Acrylic on linen',
    dimensions: '1.6m × 1.2m',
    yearMade: 2025,
    culturalStory:
      'Painting, not tatau. Tatau cannot be sold. These canvases are my conversation with tatau vocabulary, and they can travel.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-02-28T09:00:00+12:00',
  },
  {
    id: 'work_013',
    artistId: 'artist_007',
    title: 'Kapa — Hilo Rain',
    description: `A large kapa piece, beaten over six weeks. Greys and indigo referencing the rain that comes off Mauna Kea onto Hilo. This is the third piece I have made since arriving in Aotearoa.`,
    priceNzd: 8400,
    mediaRefs: ['work_013_main', 'work_013_detail_1', 'work_013_detail_2'],
    artform: 'kapa',
    nationId: 'hawaii',
    materials: 'Wauke bark, natural dyes',
    dimensions: '1.5m × 1.1m',
    yearMade: 2025,
    culturalStory:
      'Kapa is not siapo. The beating rhythm is different; the stamps are different; the dye is different. This is Hilo kapa in Aotearoa.',
    status: 'live',
    shippingFrom: 'Hamilton, Aotearoa',
    tapu: false,
    createdAt: '2026-03-30T09:00:00+12:00',
  },
  {
    id: 'work_014',
    artistId: 'artist_008',
    title: 'What the Tide Takes — II',
    description: `Cast bronze sculpture, 60cm tall, referencing a sand drawing I made in Pentecost in 2021. The drawing is gone; the bronze carries the form forward in a different register.`,
    priceNzd: 3600,
    mediaRefs: ['work_014_main', 'work_014_detail'],
    artform: 'sculpture',
    nationId: 'vanuatu',
    materials: 'Cast bronze, kauri base',
    dimensions: '60cm × 30cm × 30cm',
    edition: { number: 2, of: 5 },
    yearMade: 2024,
    culturalStory:
      'The sand drawing this references was made in Pentecost in 2021 and is long gone. The sculpture remembers it without being it.',
    status: 'live',
    shippingFrom: 'Wellington, Aotearoa',
    tapu: false,
    createdAt: '2026-01-20T09:00:00+12:00',
  },
  {
    id: 'work_015',
    artistId: 'artist_009',
    title: 'Wamage dress — Melpa Blue',
    description: `A long dress with woven bilum bodice in Melpa blue-and-ochre pattern. Eighty hours of looping; six weeks of construction.`,
    priceNzd: 1240,
    mediaRefs: ['work_015_main', 'work_015_detail_1', 'work_015_detail_2'],
    artform: 'fashion',
    nationId: 'png',
    materials: 'Woven bilum (acrylic yarn), silk underlay',
    dimensions: 'Size 12 (custom sizing available)',
    yearMade: 2025,
    culturalStory:
      'Melpa bilum vocabulary, made in Auckland. Priced for the loop-hours inside it.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-04-08T09:00:00+12:00',
  },
  {
    id: 'work_016',
    artistId: 'artist_010',
    title: 'Mouthwork — chapbook (numbered edition)',
    description: `The printed chapbook of my 2024 tour piece. 48 pages, hand-stitched binding. Numbered edition of 240.`,
    priceNzd: 45,
    mediaRefs: ['work_016_main'],
    artform: 'spoken word',
    nationId: 'aotearoa',
    materials: 'Recycled stock, hand-stitched',
    dimensions: 'A5, 48 pages',
    edition: { number: 117, of: 240 },
    yearMade: 2024,
    culturalStory: 'A zine of Mouthwork — print companion to the live work.',
    status: 'live',
    shippingFrom: 'Christchurch, Aotearoa',
    tapu: false,
    createdAt: '2024-11-14T09:00:00+12:00',
  },
  {
    id: 'work_017',
    artistId: 'artist_011',
    title: 'Shell string — ochre and mother-of-pearl',
    description: `A long shell necklace, 110cm. Ochre spondylus shells with mother-of-pearl spacers. Beach-recovered material only.`,
    priceNzd: 340,
    mediaRefs: ['work_017_main'],
    artform: 'shell jewellery',
    nationId: 'solomons',
    materials: 'Recovered spondylus shell, mother-of-pearl, waxed cotton',
    dimensions: '110cm long',
    yearMade: 2025,
    culturalStory: 'Beach-recovered shell, strung in traditional exchange-piece manner.',
    status: 'live',
    shippingFrom: 'Manukau, Aotearoa',
    tapu: false,
    createdAt: '2026-04-15T09:00:00+12:00',
  },
  {
    id: 'work_018',
    artistId: 'artist_011',
    title: 'Bone pendant — tāiko motif',
    description: `A carved bone pendant in a contemporary reading of the tāiko (storm bird) motif. Cord included.`,
    priceNzd: 85,
    mediaRefs: ['work_018_main'],
    artform: 'bone carving',
    nationId: 'solomons',
    materials: 'Sustainably-sourced cow bone, waxed cord',
    dimensions: '6cm × 3cm',
    yearMade: 2025,
    culturalStory: 'Contemporary reading of a tāiko motif. Not a ceremonial piece.',
    status: 'live',
    shippingFrom: 'Manukau, Aotearoa',
    tapu: false,
    createdAt: '2026-04-15T09:00:00+12:00',
  },
  {
    id: 'work_019',
    artistId: 'artist_012',
    title: 'Funafuti Shore — No. 6',
    description: `Photographic print, archival pigment on cotton rag. From the long-term Funafuti project. Edition of 12.`,
    priceNzd: 680,
    mediaRefs: ['work_019_main'],
    artform: 'photography',
    nationId: 'tuvalu',
    materials: 'Archival pigment print on Hahnemühle cotton rag',
    dimensions: '60cm × 90cm',
    edition: { number: 4, of: 12 },
    yearMade: 2025,
    culturalStory:
      'Part of the long Funafuti project. Funds split between film completion and Tuvalu adaptation groups.',
    status: 'live',
    shippingFrom: 'Auckland, Aotearoa',
    tapu: false,
    createdAt: '2026-02-10T09:00:00+12:00',
  },
  {
    id: 'work_020',
    artistId: 'artist_002',
    title: 'The Sea is Us — IV',
    description: `Photographic print from the 2025 solo show at Objectspace. Archival pigment, edition of 8.`,
    priceNzd: 540,
    mediaRefs: ['work_020_main'],
    artform: 'photography',
    nationId: 'tonga',
    materials: 'Archival pigment print on cotton rag',
    dimensions: '50cm × 75cm',
    edition: { number: 3, of: 8 },
    yearMade: 2025,
    culturalStory:
      'From the Objectspace 2025 show. Subject has released the image for editioned sale.',
    status: 'live',
    shippingFrom: 'Wellington, Aotearoa',
    tapu: false,
    createdAt: '2026-01-18T09:00:00+12:00',
  },
];
